### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by farnaf** [qiz013/cse15l-week-2-assignment#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - please embed the link to the VSC website and where to activate CSE15L ieng6 account
- [x] All relevant code examples written with backticks (```)
  - please format all terminal commands as code (e.g., `ls`, `scp`, `ssh-keygen`, etc.)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
  - please format the titles of each section as headers (e.g., ## Step 4)
- [x] Lab report is on its own page, not the index page
  - move the lab report files to [this repository on GitHub](https://github.com/qiz013/cse15l-lab-reports) - which is the repo for *all* your CSE15L lab reports
  - and copy the lab content to [this markdown file](https://github.com/qiz013/cse15l-lab-reports/blob/main/lab-report-1-week-2.md)
- [ ] Last example counts keystrokes and shows how to run remotely saving time
  - please make sure Step 6 on your lab report covers everything *you* did in [this part of lab 1](https://ucsd-cse15l-w22.github.io/week/week1/#part-7-making-remote-running-even-more-pleasant)
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
nice job 😃
feel free to comment below any questions related to the rubric/feedback!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by qiz013** [comment]
Dear tutor, 
Thank you so much for the comments. I have made changes except for the first comment and the second last comment.
First, what does "embed the link to the VSC website and where to activate CSE15L ieng6 account" mean? I am sorry that I do not know what the VSC website refers to. Would you please remind me of where the professor talked about this part?
Second, I follow the steps on the notes but I still get stuck when copying the public key to my account on the server. It says: 
<img width="381" alt="Screen Shot 2022-01-24 at 4 31 33 PM" src="https://user-images.githubusercontent.com/97641979/150888201-0d79348b-1e15-4269-8591-972146a01638.png">
How to solve it so that I can use the keystrokes?

**Comment by farnaf** [comment]
Hi there! Thanks for reaching out
- To check the first rubric item, you can format any URL of your choice as Markdown links (suggestions: Visual Studio Code website: https://code.visualstudio.com/ or the website where you looked up the course-specific account for CSE15: https://sdacs.ucsd.edu/~icc/index.php) by using [] and ()
- Do you get that terminal output in [this step of lab 1](https://ucsd-cse15l-w22.github.io/week/week1/#part-6--ssh-keys)? I think you can move on from that step, seems like `.ssh` is already created.

**Comment by qiz013** [comment]
Dear tutor,
Thank you for answer my questions!
However, for the second problem, I indeed get the terminal output in "this step of lab 1" as follows:
<img width="677" alt="Screen Shot 2022-01-24 at 4 15 38 PM" src="https://user-images.githubusercontent.com/97641979/151035334-83b1a773-901a-4f70-ae3f-c19c9d14f070.png">

As you guess, after listing out the all files on my ieng6 server, I do find ".ssh" created:
<img width="583" alt="Screen Shot 2022-01-25 at 10 19 04 AM" src="https://user-images.githubusercontent.com/97641979/151036270-ea2660de-859f-4a3d-a6de-489b5a942423.png">

But it seems that if I move on, I still need to manually type in/copy&paste the passwords:
<img width="556" alt="Screen Shot 2022-01-25 at 10 17 16 AM" src="https://user-images.githubusercontent.com/97641979/151035460-d6018a42-66c4-4279-9205-236ae2567ff5.png">

So what can I do to deal with it?

**Comment by farnaf** [comment]
Ah I see, the screenshots are helpful. To double check, did you also do the following steps:
- logout of your 15L account
- `scp /Users/qinxuanzhang/.ssh/id_rsa.pub cs15lwi22awo@ieng6.ucsd.edu:~/.ssh/authorized_keys`
- and then do ssh

Do you face any errors/issues for these?

**Comment by qiz013** [comment]
The issues have been solved thanks to your instructions:)
I have submit a regrade request.

**Comment by farnaf** [comment]
Thanks for submitting a regrade request! 

The second to last requirement is not quite correct yet. For the second to last requirement, come up with a command that once typed in your *local* terminal, the java program runs on the server (the computer you access when you ssh with your 15L account).

To do the above task the long way, we can (1) use scp to copy the java file over to the server (2) ssh into 15L account (3) compile the copied java file (4) run it. The goal of the last step is to come up with an optimized version of these 4 steps.

**Comment by qiz013** [comment]
Thank you so much for the detailed instruction. Hope that I get the point this time. The newest change is made in Step 6 (see screenshot7). Please have a look.

**Comment by farnaf** [comment]
Looks great! Updated your grade
